[project]
name = "fly-in"
version = "0.1.0"
description = ""
authors = [
    {name = "ymouafak"}
]
requires-python = ">=3.11"
dependencies = [
    "rich (>=15.0.0,<16.0.0)",
    "webcolors (>=25.10.0,<26.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
